TDL-684:Allowed fields to be selected via metadata
singer-io/tap-klaviyo pull request #25
Opened 2021-04-07 14:27 UTC by savan-chovatiya

# Description of change
- Allowed fields to be selected via metadata.
- Added get_standard_metadata function to generate standard metadata.
- Added transformer to transform records from the Klaviyo API to ensure they conform to the schema and metadata.

# Manual QA steps
 - Manually checked catalog file for inclusion value of fields.
 - Selected some fields in the catalog file and verified state.json for records with selected fields.
 - Run unit test case to verifying the value of inclusion for all fields.
 
# Risks
 - No Risks Found
 
# Rollback steps
 - revert this branch

2021-04-08 11:23 UTC, karanpanchal-crest approved these changes

2021-04-09 19:36 UTC, KAllan357 requested changes
As we discussed, I think we should also be marking the replication_key as automatic as well. It looks like it would be `"timestamp"`.

I'd like to see a tap-tester test which also makes assertions about the catalog's metadata here.

This also needs to be rebased or merged with master.

2021-04-12 15:47 UTC, KAllan357 commented
This will also need to rebase / merge master.

2021-04-13 08:50 UTC, savan-chovatiya commented
> As we discussed, I think we should also be marking the replication_key as automatic as well. It looks like it would be `"timestamp"`.
> 
> I'd like to see a tap-tester test which also makes assertions about the catalog's metadata here.
> 
> This also needs to be rebased or merged with master.

We have a separate ticket TDL-682 for integration tests in which we covered the catalog's metadata-related assertions under discovery mode tests so tests will be added into that PR.

2021-04-13 15:44 UTC, KAllan357 approved these changes

2021-04-13 15:44 UTC, merged